# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
# Parallel execution and build cache for fast CI builds.
org.gradle.parallel=true
org.gradle.caching=true
# AndroidX
android.useAndroidX=true
# Only keep module-specific R classes (faster builds).
android.nonTransitiveRClass=true
kotlin.code.style=official
